### ISSUE TITLE
Create specific company blacklist

### ISSUE THREAD

**Issue by kowith337** [kowith337/ThaiConsentHosts#5]
### Todo:
- Create sets of filter that blacklist specific company, for example.
  - [x] GMM Grammy (Due to it's still have `gmmwireless.com` service running, and seems to be officially supported by local mobile operator. (red color)
  - [ ] MThai`.com` (related to sub-companies under the `Jasmine`, e.g. `MonoMax`)
  - [ ] Sanook! (have `mobilemagic.sanook.com` operated in the past, may probably ignored)
    > However, the main domain already added by other repository far away as `Biased political news`
  - [x] ThaiZa (include past commits \([1](../commit/c676db969439fc2eb8ca7d12d5b1f5afd8593e8c), [2](../commit/6507aa123663f64298e4f0b07a119786608593f4)\) + search for more if needed)

**Comment by kowith337** [comment]
Project abandoned!
